apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netflix-argo-app
  namespace: argocd
spec:
  destination:
    namespace: netflix
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/baoussreda/DevSecOps-Project
    targetRevision: HEAD
    path: Kubernetes/manifests
  syncPolicy:
    automated:
      prune: true
      selfHeal: true